//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * identifier -> Identifier()
 * nodeOptional -> [ &lt;ROUNDED&gt; ]
 * </PRE>
 */
public class ArithIdentifier extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public Identifier identifier;
   public NodeOptional nodeOptional;

   public ArithIdentifier(Identifier n0, NodeOptional n1) {
      identifier = n0;
      if ( identifier != null ) identifier.setParent(this);
      nodeOptional = n1;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
   }

   public ArithIdentifier() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

