//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;CALL&gt;
 * nodeChoice -> ( Identifier() | Literal() )
 * nodeOptional -> [ &lt;USING&gt; ( ( [ [ &lt;BY&gt; ] &lt;REFERENCE&gt; ] ( CallByReferenceArgs() [ &lt;COMMACHAR&gt; ] )+ | [ &lt;BY&gt; ] ( &lt;CONTENT&gt; | &lt;VALUE&gt; ) ( CallByContentArgs() [ &lt;COMMACHAR&gt; ] )+ ) )+ ]
 * nodeOptional1 -> [ [ &lt;ON&gt; ] &lt;OVERFLOW&gt; StatementList() ]
 * nodeOptional2 -> [ [ &lt;ON&gt; ] &lt;EXCEPTION&gt; StatementList() ]
 * nodeOptional3 -> [ &lt;NOT&gt; [ &lt;ON&gt; ] &lt;EXCEPTION&gt; StatementList() ]
 * nodeOptional4 -> [ &lt;END_CALL&gt; ]
 * </PRE>
 */
public class CallStatement extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public NodeChoice nodeChoice;
   public NodeOptional nodeOptional;
   public NodeOptional nodeOptional1;
   public NodeOptional nodeOptional2;
   public NodeOptional nodeOptional3;
   public NodeOptional nodeOptional4;

   public CallStatement(NodeToken n0, NodeChoice n1, NodeOptional n2, NodeOptional n3, NodeOptional n4, NodeOptional n5, NodeOptional n6) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeChoice = n1;
      if ( nodeChoice != null ) nodeChoice.setParent(this);
      nodeOptional = n2;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      nodeOptional1 = n3;
      if ( nodeOptional1 != null ) nodeOptional1.setParent(this);
      nodeOptional2 = n4;
      if ( nodeOptional2 != null ) nodeOptional2.setParent(this);
      nodeOptional3 = n5;
      if ( nodeOptional3 != null ) nodeOptional3.setParent(this);
      nodeOptional4 = n6;
      if ( nodeOptional4 != null ) nodeOptional4.setParent(this);
   }

   public CallStatement() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

