//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * cobolWord -> CobolWord()
 * </PRE>
 */
public class CdName extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public CobolWord cobolWord;

   public CdName(CobolWord n0) {
      cobolWord = n0;
      if ( cobolWord != null ) cobolWord.setParent(this);
   }

   public CdName() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

