//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;CD&gt;
 * cdName -> CdName()
 * nodeOptional -> [ &lt;FOR&gt; ]
 * nodeToken1 -> &lt;OUTPUT&gt;
 * nodeListOptional -> ( CommunicationOutputClause() )*
 * </PRE>
 */
public class CommunicationOutputEntry extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public CdName cdName;
   public NodeOptional nodeOptional;
   public NodeToken nodeToken1;
   public NodeListOptional nodeListOptional;

   public CommunicationOutputEntry(NodeToken n0, CdName n1, NodeOptional n2, NodeToken n3, NodeListOptional n4) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      cdName = n1;
      if ( cdName != null ) cdName.setParent(this);
      nodeOptional = n2;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      nodeToken1 = n3;
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
      nodeListOptional = n4;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public CommunicationOutputEntry() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

