//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;COMPUTE&gt;
 * nodeList -> ( Identifier() [ &lt;ROUNDED&gt; ] )+
 * nodeChoice -> ( &lt;EQUALCHAR&gt; | &lt;EQUAL&gt; )
 * arithmeticExpression -> ArithmeticExpression()
 * nodeOptional -> [ [ &lt;ON&gt; ] &lt;SIZE&gt; &lt;ERROR&gt; StatementList() ]
 * nodeOptional1 -> [ &lt;NOT&gt; [ &lt;ON&gt; ] &lt;SIZE&gt; &lt;ERROR&gt; StatementList() ]
 * nodeOptional2 -> [ &lt;END_COMPUTE&gt; ]
 * </PRE>
 */
public class ComputeStatement extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public NodeList nodeList;
   public NodeChoice nodeChoice;
   public ArithmeticExpression arithmeticExpression;
   public NodeOptional nodeOptional;
   public NodeOptional nodeOptional1;
   public NodeOptional nodeOptional2;

   public ComputeStatement(NodeToken n0, NodeList n1, NodeChoice n2, ArithmeticExpression n3, NodeOptional n4, NodeOptional n5, NodeOptional n6) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeList = n1;
      if ( nodeList != null ) nodeList.setParent(this);
      nodeChoice = n2;
      if ( nodeChoice != null ) nodeChoice.setParent(this);
      arithmeticExpression = n3;
      if ( arithmeticExpression != null ) arithmeticExpression.setParent(this);
      nodeOptional = n4;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      nodeOptional1 = n5;
      if ( nodeOptional1 != null ) nodeOptional1.setParent(this);
      nodeOptional2 = n6;
      if ( nodeOptional2 != null ) nodeOptional2.setParent(this);
   }

   public ComputeStatement() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

