//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * conditionNameReference -> ConditionNameReference()
 * </PRE>
 */
public class ConditionNameCondition extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public ConditionNameReference conditionNameReference;

   public ConditionNameCondition(ConditionNameReference n0) {
      conditionNameReference = n0;
      if ( conditionNameReference != null ) conditionNameReference.setParent(this);
   }

   public ConditionNameCondition() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

