//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;K_DECLARE&gt;
 * nodeToken1 -> &lt;S_IDENTIFIER&gt;
 * nodeToken2 -> &lt;K_CURSOR&gt;
 * nodeToken3 -> &lt;K_FOR&gt;
 * nodeChoice -> ( &lt;S_IDENTIFIER&gt; | QueryStatement() )
 * </PRE>
 */
public class DeclareCursorStatement extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public NodeToken nodeToken2;
   public NodeToken nodeToken3;
   public NodeChoice nodeChoice;

   public DeclareCursorStatement(NodeToken n0, NodeToken n1, NodeToken n2, NodeToken n3, NodeChoice n4) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeToken1 = n1;
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
      nodeToken2 = n2;
      if ( nodeToken2 != null ) nodeToken2.setParent(this);
      nodeToken3 = n3;
      if ( nodeToken3 != null ) nodeToken3.setParent(this);
      nodeChoice = n4;
      if ( nodeChoice != null ) nodeChoice.setParent(this);
   }

   public DeclareCursorStatement() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

