//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeChoice -> &lt;ZERO&gt;
 *       | &lt;ZEROS&gt;
 *       | &lt;ZEROES&gt;
 *       | &lt;SPACE&gt;
 *       | &lt;SPACES&gt;
 *       | &lt;HIGH_VALUE&gt;
 *       | &lt;HIGH_VALUES&gt;
 *       | &lt;LOW_VALUE&gt;
 *       | &lt;LOW_VALUES&gt;
 *       | &lt;QUOTE&gt;
 *       | &lt;QUOTES&gt;
 *       | &lt;NULL&gt;
 *       | &lt;NULLS&gt;
 * </PRE>
 */
public class FigurativeConstant extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeChoice nodeChoice;

   public FigurativeConstant(NodeChoice n0) {
      nodeChoice = n0;
      if ( nodeChoice != null ) nodeChoice.setParent(this);
   }

   public FigurativeConstant() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

