//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;K_GROUP&gt;
 * nodeToken1 -> &lt;K_BY&gt;
 * sQLExpressionList -> SQLExpressionList()
 * nodeOptional -> [ &lt;K_HAVING&gt; SQLExpression() ]
 * </PRE>
 */
public class GroupByClause extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public SQLExpressionList sQLExpressionList;
   public NodeOptional nodeOptional;

   public GroupByClause(NodeToken n0, NodeToken n1, SQLExpressionList n2, NodeOptional n3) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeToken1 = n1;
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
      sQLExpressionList = n2;
      if ( sQLExpressionList != null ) sQLExpressionList.setParent(this);
      nodeOptional = n3;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
   }

   public GroupByClause() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

