//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;K_LOCK&gt;
 * nodeToken1 -> &lt;K_TABLE&gt;
 * tableReference -> TableReference()
 * nodeListOptional -> ( &lt;COMMACHAR&gt; TableReference() )*
 * nodeToken2 -> &lt;K_IN&gt;
 * lockMode -> LockMode()
 * nodeToken3 -> &lt;K_MODE&gt;
 * nodeOptional -> [ &lt;K_NOWAIT&gt; ]
 * </PRE>
 */
public class LockTableStatement extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public TableReference tableReference;
   public NodeListOptional nodeListOptional;
   public NodeToken nodeToken2;
   public LockMode lockMode;
   public NodeToken nodeToken3;
   public NodeOptional nodeOptional;

   public LockTableStatement(NodeToken n0, NodeToken n1, TableReference n2, NodeListOptional n3, NodeToken n4, LockMode n5, NodeToken n6, NodeOptional n7) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeToken1 = n1;
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
      tableReference = n2;
      if ( tableReference != null ) tableReference.setParent(this);
      nodeListOptional = n3;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
      nodeToken2 = n4;
      if ( nodeToken2 != null ) nodeToken2.setParent(this);
      lockMode = n5;
      if ( lockMode != null ) lockMode.setParent(this);
      nodeToken3 = n6;
      if ( nodeToken3 != null ) nodeToken3.setParent(this);
      nodeOptional = n7;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
   }

   public LockTableStatement() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

