//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;MERGE&gt;
 * fileName -> FileName()
 * nodeList -> ( [ &lt;ON&gt; ] ( &lt;ASCENDING&gt; | &lt;DESCENDING&gt; ) [ &lt;KEY&gt; ] ( QualifiedDataName() [ &lt;COMMACHAR&gt; ] )+ )+
 * nodeOptional -> [ [ &lt;COLLATING&gt; ] &lt;SEQUENCE&gt; [ &lt;IS&gt; ] AlphabetName() ]
 * nodeToken1 -> &lt;USING&gt;
 * fileName1 -> FileName()
 * nodeList1 -> ( [ &lt;COMMACHAR&gt; ] FileName() )+
 * nodeChoice -> ( &lt;OUTPUT&gt; &lt;PROCEDURE&gt; [ &lt;IS&gt; ] ProcedureName() [ ( &lt;THROUGH&gt; | &lt;THRU&gt; ) ProcedureName() ] | &lt;GIVING&gt; ( FileName() )+ )
 * </PRE>
 */
public class MergeStatement extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public FileName fileName;
   public NodeList nodeList;
   public NodeOptional nodeOptional;
   public NodeToken nodeToken1;
   public FileName fileName1;
   public NodeList nodeList1;
   public NodeChoice nodeChoice;

   public MergeStatement(NodeToken n0, FileName n1, NodeList n2, NodeOptional n3, NodeToken n4, FileName n5, NodeList n6, NodeChoice n7) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      fileName = n1;
      if ( fileName != null ) fileName.setParent(this);
      nodeList = n2;
      if ( nodeList != null ) nodeList.setParent(this);
      nodeOptional = n3;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      nodeToken1 = n4;
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
      fileName1 = n5;
      if ( fileName1 != null ) fileName1.setParent(this);
      nodeList1 = n6;
      if ( nodeList1 != null ) nodeList1.setParent(this);
      nodeChoice = n7;
      if ( nodeChoice != null ) nodeChoice.setParent(this);
   }

   public MergeStatement() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

