//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * plSqlExpression -> PlSqlExpression()
 * nodeListOptional -> ( &lt;COMMACHAR&gt; PlSqlExpression() )*
 * </PRE>
 */
public class PlSqlExpressionList extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public PlSqlExpression plSqlExpression;
   public NodeListOptional nodeListOptional;

   public PlSqlExpressionList(PlSqlExpression n0, NodeListOptional n1) {
      plSqlExpression = n0;
      if ( plSqlExpression != null ) plSqlExpression.setParent(this);
      nodeListOptional = n1;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public PlSqlExpressionList() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

