//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * plSqlSimpleExpressions -> PlSqlSimpleExpressions()
 * </PRE>
 */
public class PlSqlSimpleExpression extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public PlSqlSimpleExpressions plSqlSimpleExpressions;

   public PlSqlSimpleExpression(PlSqlSimpleExpressions n0) {
      plSqlSimpleExpressions = n0;
      if ( plSqlSimpleExpressions != null ) plSqlSimpleExpressions.setParent(this);
   }

   public PlSqlSimpleExpression() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

