//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeChoice -> ( &lt;PROCEDURE&gt; &lt;DIVISION&gt; | &lt;PROCEDURE_DIVISION&gt; )
 * nodeOptional -> [ [ &lt;DOT&gt; ] UsingArgs() ]
 * nodeToken -> &lt;DOT&gt;
 * nodeOptional1 -> [ Declaratives() ]
 * procedureBody -> ProcedureBody()
 * </PRE>
 */
public class ProcedureDivision extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeChoice nodeChoice;
   public NodeOptional nodeOptional;
   public NodeToken nodeToken;
   public NodeOptional nodeOptional1;
   public ProcedureBody procedureBody;

   public ProcedureDivision(NodeChoice n0, NodeOptional n1, NodeToken n2, NodeOptional n3, ProcedureBody n4) {
      nodeChoice = n0;
      if ( nodeChoice != null ) nodeChoice.setParent(this);
      nodeOptional = n1;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      nodeToken = n2;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeOptional1 = n3;
      if ( nodeOptional1 != null ) nodeOptional1.setParent(this);
      procedureBody = n4;
      if ( procedureBody != null ) procedureBody.setParent(this);
   }

   public ProcedureDivision() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

