//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * arithmeticExpression -> ArithmeticExpression()
 * nodeChoice -> ( RelationalOperator() ArithmeticExpression() | SignCondition() )
 * </PRE>
 */
public class RelationCondition extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public ArithmeticExpression arithmeticExpression;
   public NodeChoice nodeChoice;

   public RelationCondition(ArithmeticExpression n0, NodeChoice n1) {
      arithmeticExpression = n0;
      if ( arithmeticExpression != null ) arithmeticExpression.setParent(this);
      nodeChoice = n1;
      if ( nodeChoice != null ) nodeChoice.setParent(this);
   }

   public RelationCondition() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

