//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;SEARCH&gt;
 * nodeOptional -> [ &lt;ALL&gt; ]
 * qualifiedDataName -> QualifiedDataName()
 * nodeOptional1 -> [ &lt;VARYING&gt; QualifiedDataName() ]
 * nodeOptional2 -> [ [ &lt;AT&gt; ] &lt;END&gt; StatementList() ]
 * nodeList -> ( &lt;WHEN&gt; Condition() ( StatementList() | &lt;NEXT&gt; &lt;SENTENCE&gt; ) )+
 * nodeOptional3 -> [ &lt;END_SEARCH&gt; ]
 * </PRE>
 */
public class SearchStatement extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public NodeOptional nodeOptional;
   public QualifiedDataName qualifiedDataName;
   public NodeOptional nodeOptional1;
   public NodeOptional nodeOptional2;
   public NodeList nodeList;
   public NodeOptional nodeOptional3;

   public SearchStatement(NodeToken n0, NodeOptional n1, QualifiedDataName n2, NodeOptional n3, NodeOptional n4, NodeList n5, NodeOptional n6) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeOptional = n1;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      qualifiedDataName = n2;
      if ( qualifiedDataName != null ) qualifiedDataName.setParent(this);
      nodeOptional1 = n3;
      if ( nodeOptional1 != null ) nodeOptional1.setParent(this);
      nodeOptional2 = n4;
      if ( nodeOptional2 != null ) nodeOptional2.setParent(this);
      nodeList = n5;
      if ( nodeList != null ) nodeList.setParent(this);
      nodeOptional3 = n6;
      if ( nodeOptional3 != null ) nodeOptional3.setParent(this);
   }

   public SearchStatement() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

