//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * sectionName -> SectionName()
 * nodeToken -> &lt;SECTION&gt;
 * nodeOptional -> [ IntegerConstant() ]
 * </PRE>
 */
public class SectionHeader extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public SectionName sectionName;
   public NodeToken nodeToken;
   public NodeOptional nodeOptional;

   public SectionHeader(SectionName n0, NodeToken n1, NodeOptional n2) {
      sectionName = n0;
      if ( sectionName != null ) sectionName.setParent(this);
      nodeToken = n1;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeOptional = n2;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
   }

   public SectionHeader() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

