//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * sQLSimpleExpression -> SQLSimpleExpression()
 * nodeListOptional -> ( &lt;COMMACHAR&gt; SQLSimpleExpression() )*
 * </PRE>
 */
public class SQLExpressionList extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public SQLSimpleExpression sQLSimpleExpression;
   public NodeListOptional nodeListOptional;

   public SQLExpressionList(SQLSimpleExpression n0, NodeListOptional n1) {
      sQLSimpleExpression = n0;
      if ( sQLSimpleExpression != null ) sQLSimpleExpression.setParent(this);
      nodeListOptional = n1;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public SQLExpressionList() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

