//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * sQLAndExpressions -> SQLAndExpressions()
 * nodeList -> ( &lt;K_OR&gt; SQLAndExpressions() )+
 * </PRE>
 */
public class SQLOrExpression extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public SQLAndExpressions sQLAndExpressions;
   public NodeList nodeList;

   public SQLOrExpression(SQLAndExpressions n0, NodeList n1) {
      sQLAndExpressions = n0;
      if ( sQLAndExpressions != null ) sQLAndExpressions.setParent(this);
      nodeList = n1;
      if ( nodeList != null ) nodeList.setParent(this);
   }

   public SQLOrExpression() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

