//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;SYMBOLIC&gt;
 * nodeOptional -> [ &lt;CHARACTERS&gt; ]
 * nodeList -> ( ( SymbolicCharacter() )+ [ ( &lt;ARE&gt; | &lt;IS&gt; ) ] ( IntegerConstant() )+ )+
 * nodeOptional1 -> [ &lt;IN&gt; AlphabetName() ]
 * </PRE>
 */
public class SymbolicCharactersClause extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public NodeOptional nodeOptional;
   public NodeList nodeList;
   public NodeOptional nodeOptional1;

   public SymbolicCharactersClause(NodeToken n0, NodeOptional n1, NodeList n2, NodeOptional n3) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeOptional = n1;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      nodeList = n2;
      if ( nodeList != null ) nodeList.setParent(this);
      nodeOptional1 = n3;
      if ( nodeOptional1 != null ) nodeOptional1.setParent(this);
   }

   public SymbolicCharactersClause() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

