//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * identifier -> Identifier()
 * nodeOptional -> [ &lt;IS&gt; ]
 * nodeOptional1 -> [ &lt;NOT&gt; ]
 * nodeChoice -> ( &lt;NUMERIC&gt; | &lt;ALPHABETIC&gt; | &lt;ALPHABETIC_LOWER&gt; | &lt;ALPHABETIC_UPPER&gt; | ClassName() | &lt;DBCS&gt; | &lt;KANJI&gt; )
 * </PRE>
 */
public class ClassCondition extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public Identifier identifier;
   public NodeOptional nodeOptional;
   public NodeOptional nodeOptional1;
   public NodeChoice nodeChoice;

   public ClassCondition(Identifier n0, NodeOptional n1, NodeOptional n2, NodeChoice n3) {
      identifier = n0;
      if ( identifier != null ) identifier.setParent(this);
      nodeOptional = n1;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      nodeOptional1 = n2;
      if ( nodeOptional1 != null ) nodeOptional1.setParent(this);
      nodeChoice = n3;
      if ( nodeChoice != null ) nodeChoice.setParent(this);
   }

   public ClassCondition() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

