//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeOptional -> [ &lt;PROGRAM&gt; ]
 * nodeOptional1 -> [ &lt;COLLATING&gt; ]
 * nodeToken -> &lt;SEQUENCE&gt;
 * nodeOptional2 -> [ &lt;IS&gt; ]
 * alphabetName -> AlphabetName()
 * </PRE>
 */
public class CollatingSequenceClause extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeOptional nodeOptional;
   public NodeOptional nodeOptional1;
   public NodeToken nodeToken;
   public NodeOptional nodeOptional2;
   public AlphabetName alphabetName;

   public CollatingSequenceClause(NodeOptional n0, NodeOptional n1, NodeToken n2, NodeOptional n3, AlphabetName n4) {
      nodeOptional = n0;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      nodeOptional1 = n1;
      if ( nodeOptional1 != null ) nodeOptional1.setParent(this);
      nodeToken = n2;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeOptional2 = n3;
      if ( nodeOptional2 != null ) nodeOptional2.setParent(this);
      alphabetName = n4;
      if ( alphabetName != null ) alphabetName.setParent(this);
   }

   public CollatingSequenceClause() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

