//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;CD&gt;
 * cdName -> CdName()
 * nodeOptional -> [ &lt;FOR&gt; ]
 * nodeOptional1 -> [ &lt;INITIAL&gt; ]
 * nodeToken1 -> &lt;INPUT&gt;
 * nodeListOptional -> ( CommunicationInputClause() )*
 * nodeListOptional1 -> ( DataName() | &lt;FILLER&gt; )*
 * </PRE>
 */
public class CommunicationInputEntry extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public CdName cdName;
   public NodeOptional nodeOptional;
   public NodeOptional nodeOptional1;
   public NodeToken nodeToken1;
   public NodeListOptional nodeListOptional;
   public NodeListOptional nodeListOptional1;

   public CommunicationInputEntry(NodeToken n0, CdName n1, NodeOptional n2, NodeOptional n3, NodeToken n4, NodeListOptional n5, NodeListOptional n6) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      cdName = n1;
      if ( cdName != null ) cdName.setParent(this);
      nodeOptional = n2;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      nodeOptional1 = n3;
      if ( nodeOptional1 != null ) nodeOptional1.setParent(this);
      nodeToken1 = n4;
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
      nodeListOptional = n5;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
      nodeListOptional1 = n6;
      if ( nodeListOptional1 != null ) nodeListOptional1.setParent(this);
   }

   public CommunicationInputEntry() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

