//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeChoice -> ( &lt;PICTURE&gt; | &lt;PIC&gt; )
 * nodeOptional -> [ &lt;IS&gt; ]
 * pictureString -> PictureString()
 * nodeOptional1 -> [ &lt;VARYING&gt; ]
 * </PRE>
 */
public class DataPictureClause extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeChoice nodeChoice;
   public NodeOptional nodeOptional;
   public PictureString pictureString;
   public NodeOptional nodeOptional1;

   public DataPictureClause(NodeChoice n0, NodeOptional n1, PictureString n2, NodeOptional n3) {
      nodeChoice = n0;
      if ( nodeChoice != null ) nodeChoice.setParent(this);
      nodeOptional = n1;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      pictureString = n2;
      if ( pictureString != null ) pictureString.setParent(this);
      nodeOptional1 = n3;
      if ( nodeOptional1 != null ) nodeOptional1.setParent(this);
   }

   public DataPictureClause() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

