//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;ENABLE&gt;
 * nodeChoice -> ( &lt;INPUT&gt; [ &lt;TERMINAL&gt; ] | &lt;OUTPUT&gt; )
 * nodeChoice1 -> ( Identifier() | Literal() )
 * nodeOptional -> [ &lt;WITH&gt; ]
 * nodeToken1 -> &lt;KEY&gt;
 * nodeChoice2 -> ( Identifier() | Literal() )
 * </PRE>
 */
public class EnableStatement extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public NodeChoice nodeChoice;
   public NodeChoice nodeChoice1;
   public NodeOptional nodeOptional;
   public NodeToken nodeToken1;
   public NodeChoice nodeChoice2;

   public EnableStatement(NodeToken n0, NodeChoice n1, NodeChoice n2, NodeOptional n3, NodeToken n4, NodeChoice n5) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeChoice = n1;
      if ( nodeChoice != null ) nodeChoice.setParent(this);
      nodeChoice1 = n2;
      if ( nodeChoice1 != null ) nodeChoice1.setParent(this);
      nodeOptional = n3;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      nodeToken1 = n4;
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
      nodeChoice2 = n5;
      if ( nodeChoice2 != null ) nodeChoice2.setParent(this);
   }

   public EnableStatement() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

