//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;K_ORDER&gt;
 * nodeToken1 -> &lt;K_BY&gt;
 * sQLSimpleExpression -> SQLSimpleExpression()
 * nodeOptional -> [ &lt;K_ASC&gt; | &lt;K_DESC&gt; ]
 * nodeListOptional -> ( &lt;COMMACHAR&gt; SQLSimpleExpression() [ &lt;K_ASC&gt; | &lt;K_DESC&gt; ] )*
 * </PRE>
 */
public class OrderByClause extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public SQLSimpleExpression sQLSimpleExpression;
   public NodeOptional nodeOptional;
   public NodeListOptional nodeListOptional;

   public OrderByClause(NodeToken n0, NodeToken n1, SQLSimpleExpression n2, NodeOptional n3, NodeListOptional n4) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeToken1 = n1;
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
      sQLSimpleExpression = n2;
      if ( sQLSimpleExpression != null ) sQLSimpleExpression.setParent(this);
      nodeOptional = n3;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      nodeListOptional = n4;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public OrderByClause() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

