//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeChoice -> &lt;SLASHCHAR&gt;
 *       | &lt;COMMACHAR&gt;
 *       | &lt;COLONCHAR&gt;
 *       | &lt;ASTERISKCHAR&gt;
 *       | &lt;MINUSCHAR&gt;
 *       | &lt;PLUSCHAR&gt;
 *       | &lt;POW&gt;
 *       | &lt;LESSTHANOREQUAL&gt;
 *       | &lt;LESSTHANCHAR&gt;
 *       | &lt;MORETHANOREQUAL&gt;
 *       | &lt;MORETHANCHAR&gt;
 *       | &lt;EQUALCHAR&gt;
 *       | &lt;NOTEQUALCHAR&gt;
 * </PRE>
 */
public class PicturePunctuation extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeChoice nodeChoice;

   public PicturePunctuation(NodeChoice n0) {
      nodeChoice = n0;
      if ( nodeChoice != null ) nodeChoice.setParent(this);
   }

   public PicturePunctuation() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

