//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * pictureOccurence -> PictureOccurence()
 * nodeListOptional -> ( &lt;DOTCHAR&gt; PictureOccurence() | PictureOccurence() )*
 * nodeListOptional1 -> ( &lt;DOTCHAR&gt; )*
 * </PRE>
 */
public class PictureString extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public PictureOccurence pictureOccurence;
   public NodeListOptional nodeListOptional;
   public NodeListOptional nodeListOptional1;

   public PictureString(PictureOccurence n0, NodeListOptional n1, NodeListOptional n2) {
      pictureOccurence = n0;
      if ( pictureOccurence != null ) pictureOccurence.setParent(this);
      nodeListOptional = n1;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
      nodeListOptional1 = n2;
      if ( nodeListOptional1 != null ) nodeListOptional1.setParent(this);
   }

   public PictureString() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

