//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * plSqlAndExpressions -> PlSqlAndExpressions()
 * nodeList -> ( &lt;K_OR&gt; PlSqlAndExpressions() )+
 * </PRE>
 */
public class PlSqlOrExpression extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public PlSqlAndExpressions plSqlAndExpressions;
   public NodeList nodeList;

   public PlSqlOrExpression(PlSqlAndExpressions n0, NodeList n1) {
      plSqlAndExpressions = n0;
      if ( plSqlAndExpressions != null ) plSqlAndExpressions.setParent(this);
      nodeList = n1;
      if ( nodeList != null ) nodeList.setParent(this);
   }

   public PlSqlOrExpression() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

