//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * plSqlSimpleExpressions -> PlSqlSimpleExpressions()
 * nodeChoice -> ( Relop() PlSqlSimpleExpressions() | PlSqlInClause() | PlSqlBetweenClause() | PlSqlLikeClause() | IsNullClause() )
 * </PRE>
 */
public class PlSqlRelationalExpression extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public PlSqlSimpleExpressions plSqlSimpleExpressions;
   public NodeChoice nodeChoice;

   public PlSqlRelationalExpression(PlSqlSimpleExpressions n0, NodeChoice n1) {
      plSqlSimpleExpressions = n0;
      if ( plSqlSimpleExpressions != null ) plSqlSimpleExpressions.setParent(this);
      nodeChoice = n1;
      if ( nodeChoice != null ) nodeChoice.setParent(this);
   }

   public PlSqlRelationalExpression() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

