//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * sectionHeader -> SectionHeader()
 * nodeToken -> &lt;DOT&gt;
 * paragraphs -> Paragraphs()
 * </PRE>
 */
public class ProcedureSection extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public SectionHeader sectionHeader;
   public NodeToken nodeToken;
   public Paragraphs paragraphs;

   public ProcedureSection(SectionHeader n0, NodeToken n1, Paragraphs n2) {
      sectionHeader = n0;
      if ( sectionHeader != null ) sectionHeader.setParent(this);
      nodeToken = n1;
      if ( nodeToken != null ) nodeToken.setParent(this);
      paragraphs = n2;
      if ( paragraphs != null ) paragraphs.setParent(this);
   }

   public ProcedureSection() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

