//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;SAME&gt;
 * nodeOptional -> [ &lt;RECORD&gt; | &lt;SORT&gt; | &lt;SORT_MERGE&gt; ]
 * nodeOptional1 -> [ &lt;AREA&gt; ]
 * nodeOptional2 -> [ &lt;FOR&gt; ]
 * nodeList -> ( FileName() [ &lt;COMMACHAR&gt; ] )+
 * </PRE>
 */
public class SameAreaClause extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public NodeOptional nodeOptional;
   public NodeOptional nodeOptional1;
   public NodeOptional nodeOptional2;
   public NodeList nodeList;

   public SameAreaClause(NodeToken n0, NodeOptional n1, NodeOptional n2, NodeOptional n3, NodeList n4) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeOptional = n1;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      nodeOptional1 = n2;
      if ( nodeOptional1 != null ) nodeOptional1.setParent(this);
      nodeOptional2 = n3;
      if ( nodeOptional2 != null ) nodeOptional2.setParent(this);
      nodeList = n4;
      if ( nodeList != null ) nodeList.setParent(this);
   }

   public SameAreaClause() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

