//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;K_SAVEPOINT&gt;
 * relObjectName -> RelObjectName()
 * </PRE>
 */
public class SavepointStatement extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public RelObjectName relObjectName;

   public SavepointStatement(NodeToken n0, RelObjectName n1) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      relObjectName = n1;
      if ( relObjectName != null ) relObjectName.setParent(this);
   }

   public SavepointStatement() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

