//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;K_SELECT&gt;
 * nodeOptional -> [ &lt;K_ALL&gt; | &lt;K_DISTINCT&gt; ]
 * selectList -> SelectList()
 * nodeOptional1 -> [ IntoClause() ]
 * fromClause -> FromClause()
 * nodeOptional2 -> [ WhereClause() ]
 * nodeOptional3 -> [ ConnectClause() ]
 * nodeOptional4 -> [ GroupByClause() ]
 * nodeOptional5 -> [ SetClause() ]
 * </PRE>
 */
public class SelectWithoutOrder extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public NodeOptional nodeOptional;
   public SelectList selectList;
   public NodeOptional nodeOptional1;
   public FromClause fromClause;
   public NodeOptional nodeOptional2;
   public NodeOptional nodeOptional3;
   public NodeOptional nodeOptional4;
   public NodeOptional nodeOptional5;

   public SelectWithoutOrder(NodeToken n0, NodeOptional n1, SelectList n2, NodeOptional n3, FromClause n4, NodeOptional n5, NodeOptional n6, NodeOptional n7, NodeOptional n8) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeOptional = n1;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      selectList = n2;
      if ( selectList != null ) selectList.setParent(this);
      nodeOptional1 = n3;
      if ( nodeOptional1 != null ) nodeOptional1.setParent(this);
      fromClause = n4;
      if ( fromClause != null ) fromClause.setParent(this);
      nodeOptional2 = n5;
      if ( nodeOptional2 != null ) nodeOptional2.setParent(this);
      nodeOptional3 = n6;
      if ( nodeOptional3 != null ) nodeOptional3.setParent(this);
      nodeOptional4 = n7;
      if ( nodeOptional4 != null ) nodeOptional4.setParent(this);
      nodeOptional5 = n8;
      if ( nodeOptional5 != null ) nodeOptional5.setParent(this);
   }

   public SelectWithoutOrder() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

