//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * sQLUnaryLogicalExpressions -> SQLUnaryLogicalExpressions()
 * nodeList -> ( &lt;K_AND&gt; SQLUnaryLogicalExpressions() )+
 * </PRE>
 */
public class SQLAndExpression extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public SQLUnaryLogicalExpressions sQLUnaryLogicalExpressions;
   public NodeList nodeList;

   public SQLAndExpression(SQLUnaryLogicalExpressions n0, NodeList n1) {
      sQLUnaryLogicalExpressions = n0;
      if ( sQLUnaryLogicalExpressions != null ) sQLUnaryLogicalExpressions.setParent(this);
      nodeList = n1;
      if ( nodeList != null ) nodeList.setParent(this);
   }

   public SQLAndExpression() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

