//
// Generated by JTB 1.3.2
//

package com.res.cobol.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * sQLExpotentExpressions -> SQLExpotentExpressions()
 * nodeList -> ( ( &lt;ASTERISKCHAR&gt; | &lt;SLASHCHAR&gt; ) SQLExpotentExpressions() )+
 * </PRE>
 */
public class SQLMultiplicativeExpression extends com.res.cobol.RESNode implements Node {
   private Node parent;
   public SQLExpotentExpressions sQLExpotentExpressions;
   public NodeList nodeList;

   public SQLMultiplicativeExpression(SQLExpotentExpressions n0, NodeList n1) {
      sQLExpotentExpressions = n0;
      if ( sQLExpotentExpressions != null ) sQLExpotentExpressions.setParent(this);
      nodeList = n1;
      if ( nodeList != null ) nodeList.setParent(this);
   }

   public SQLMultiplicativeExpression() {}

   public void accept(com.res.cobol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(com.res.cobol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(com.res.cobol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(com.res.cobol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

