java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC101A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC102A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC103A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC104A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC105A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC106A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC107A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC108M.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC109M.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC110M.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC111A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC112A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC113M.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC114M.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC115A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC116A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC117A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC118A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC119A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC120A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC121M.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC122A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC123A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC124A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC125A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC126A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC127A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC131A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC132A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC133A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC134A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC135A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC136A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC137A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC138A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC139A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC140A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC141A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC170A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC171A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC172A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC173A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC174A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC175A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC176A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC177A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC201A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC202A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC203A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC204M.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC205A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC206A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC207A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC208A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC209A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC210A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC211A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC214M.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC215A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC216A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC217A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC218A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC219A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC220M.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC221A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC222A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC223A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC224A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC225A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC231A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC232A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC233A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC234A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC235A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC236A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC237A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC238A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC239A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC240A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC241A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC242A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC243A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC244A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC245A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC246A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC247A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC248A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC250A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC251A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC252A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC253A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC254A.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC302M.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC303M.COB >>$run.log 2>>$err.log
java -jar ..\RES.jar -opt2 -c3  -dp1 -overwrite NC401M.COB >>$run.log 2>>$err.log

